# Categories taken from https://mailchimp.com/resources/top-online-shopping-categories/
CAT_ELECTRONIC = 'Electronics'
CAT_FASHION = 'Fashion'
CAT_TOY_HOBBY = 'Toys and Hobbies'
CAT_DIGITAL_SERVICES = 'Digital Services'
CAT_COSMETICS_BODY = 'Cosmetics and Body Care'
CAT_FOOD_BEV = 'Food and Beverage'
CAT_FURNITURE = 'Furniture and Decor'
CAT_HEALTH = 'Health and Wellness'
CAT_HOUSEHOLD = 'Household Items'
CAT_MEDIA = 'Media'
CAT_PET = 'Pet Care'
CAT_OFFICE = 'Office Equipment'

"""
Mercari's categories are manually mapped to MailChimp's categories
"""
CATEGORY_MAP = {
    'Beauty': CAT_COSMETICS_BODY,
    'Electronics': {
        'Cameras & Photography': CAT_ELECTRONIC,
        'Car Audio, Video & GPS': CAT_ELECTRONIC,
        'Cell Phones & Accessories': CAT_ELECTRONIC,
        'Computers & Tablets': CAT_ELECTRONIC,
        'Media': CAT_MEDIA,
        'TV, Audio & Surveillance': CAT_ELECTRONIC,
        'Video Games & Consoles': {
            'Accessories': CAT_ELECTRONIC,
            'Consoles': CAT_ELECTRONIC,
            'Games': CAT_MEDIA,
            'Replacement Parts & Tools': CAT_ELECTRONIC,
            'Strategy Guides': CAT_MEDIA,
            'Video Gaming Merchandise': CAT_TOY_HOBBY,
        },
    },
    'Handmade': {
        'Accessories': CAT_FASHION,
        'Art': CAT_MEDIA,
        'Bags and Purses': CAT_FASHION,
        'Books and Zines': {
            'Album': CAT_HOUSEHOLD,
            'Book': CAT_MEDIA,
            'Bookmark': CAT_OFFICE,
            'Comic': CAT_MEDIA,
            'Journal': CAT_OFFICE,
            'Zine': CAT_MEDIA,
        },
        'Candles': {
            'Bookmark': CAT_HOUSEHOLD,
            'Calendar': CAT_HOUSEHOLD,
            'Cards': CAT_HOUSEHOLD,
            'Other': CAT_HOUSEHOLD,
            'Scrapbooking': CAT_OFFICE,
            'Stationery': CAT_OFFICE,
            'Sticker': CAT_OFFICE,
        },
        'Ceramics and Pottery': CAT_HOUSEHOLD,
        'Children': {
            'Accessories': CAT_FASHION,
            'Art': CAT_TOY_HOBBY,
            'Baby': CAT_FASHION,
            'Bath': CAT_HOUSEHOLD,
            'Clothing': CAT_FASHION,
            'Furniture': CAT_FURNITURE,
            'Housewares': CAT_HOUSEHOLD,
            'Jewelry': CAT_FASHION,
            'Toddler': CAT_FASHION,
            'Toy': CAT_TOY_HOBBY,
        },
        'Clothing': CAT_FASHION,
        'Crochet': {
            'Accessories': CAT_FASHION,
            'Afghan': CAT_HOUSEHOLD,
            'Bags and Purses': CAT_FASHION,
            'Clothing': CAT_FASHION,
            'Doll': CAT_TOY_HOBBY,
            'Jewelry': CAT_FASHION,
            'Hat': CAT_FASHION,
            'Housewares': CAT_HOUSEHOLD,
            'Scarf': CAT_FASHION,
            'Supplies': CAT_TOY_HOBBY,
        },
        'Dolls and Miniatures': CAT_TOY_HOBBY,
        'Furniture': CAT_FURNITURE,
        'Geekery': CAT_TOY_HOBBY,
        'Glass': {
            'Beads': CAT_TOY_HOBBY,
            'Bottles': CAT_HOUSEHOLD,
            'Bowls': CAT_HOUSEHOLD,
            'Dishes': CAT_HOUSEHOLD,
            'Glassware': CAT_HOUSEHOLD,
            'Home Decor': CAT_FURNITURE,
            'Jewelry': CAT_FASHION,
            'Marbles': CAT_TOY_HOBBY,
            'Mirrors': CAT_HOUSEHOLD,
            'Ornaments': CAT_FURNITURE,
            'Paperweights': CAT_HOUSEHOLD,
            'Sculptures': CAT_TOY_HOBBY,
            'Stained Glass': CAT_FURNITURE,
            'Supplies': CAT_TOY_HOBBY,
            'Vases': CAT_HOUSEHOLD,
            'Windchimes': CAT_HOUSEHOLD,
        },
        'Holidays': CAT_HOUSEHOLD,
        'Housewares': CAT_HOUSEHOLD,
        'Jewelry': {
            'Books and Zines': CAT_MEDIA,
            'Clothing': CAT_FASHION,
            'Jewelry': CAT_FASHION,
            'Music': CAT_MEDIA,
        },
        'Knitting': {
            'Accessories': CAT_HOUSEHOLD,
            'Baby': CAT_TOY_HOBBY,
            'Bags and Purses': CAT_FASHION,
            'Blanket': CAT_HOUSEHOLD,
            'Children': CAT_TOY_HOBBY,
            'Clothing': CAT_FASHION,
            'Cozy': CAT_TOY_HOBBY,
            'Doll': CAT_TOY_HOBBY,
            'Hat': CAT_FASHION,
            'Knitting Supplies': CAT_HOUSEHOLD,
            'Scarf': CAT_FASHION,
            'Women': CAT_FASHION,
        },
        'Music': {
            'Case': CAT_HOUSEHOLD,
            'Equipment': CAT_HOUSEHOLD,
            'Instrument': CAT_HOUSEHOLD,
            'Poster': CAT_FURNITURE,
            'Tape': CAT_MEDIA,
            'Vinyl': CAT_MEDIA,
        },
        'Needlecraft': {
            'Accessories': CAT_TOY_HOBBY,
            'Clothing': CAT_TOY_HOBBY,
            'Cross Stitch': CAT_TOY_HOBBY,
            'Doll': CAT_TOY_HOBBY,
            'Embroidery': CAT_TOY_HOBBY,
            'Felted': CAT_TOY_HOBBY,
            'Holidays': CAT_TOY_HOBBY,
            'Needlepoint': CAT_TOY_HOBBY,
            'Pattern': CAT_TOY_HOBBY,
            'Pillow': CAT_HOUSEHOLD,
            'Pincushion': CAT_TOY_HOBBY,
            'Supplies': CAT_TOY_HOBBY,
        },
        'Others': {
            'Educational': CAT_MEDIA,
            'Graphic Design': CAT_FURNITURE,
            'Magic': CAT_TOY_HOBBY,
            'Religious': CAT_FURNITURE,
        },
        'Paper Goods': {
            'Bookmark': CAT_OFFICE,
            'Calendar': CAT_HOUSEHOLD,
            'Cards': CAT_TOY_HOBBY,
            'Gift Wrap': CAT_HOUSEHOLD,
            'Journal': CAT_OFFICE,
            'Notebook': CAT_OFFICE,
            'Origami': CAT_TOY_HOBBY,
            'Pad': CAT_OFFICE,
            'Papermaking': CAT_TOY_HOBBY,
            'Scrapbooking': CAT_TOY_HOBBY,
            'Stationery': CAT_OFFICE,
            'Sticker': CAT_HOUSEHOLD,
            'Tag': CAT_HOUSEHOLD,
        },
        'Patterns': {
            'Accessories': CAT_FASHION,
            'Baby': CAT_FASHION,
            'Beading': CAT_TOY_HOBBY,
            'Crochet': CAT_FASHION,
            'Cross Stitch': CAT_TOY_HOBBY,
            'Doll Clothing': CAT_TOY_HOBBY,
            'Embroidery': CAT_FASHION,
            'Handmade': CAT_HOUSEHOLD,
            'Knitting': CAT_HOUSEHOLD,
            'Painting': CAT_TOY_HOBBY,
            'Plushie': CAT_TOY_HOBBY,
            'Quilt': CAT_HOUSEHOLD,
            'Sewing': CAT_HOUSEHOLD,
        },
        'Pets': CAT_PET,
        'Quilts': CAT_HOUSEHOLD,
        'Toys': CAT_TOY_HOBBY,
        'Weddings': {
            'Accessories': CAT_FASHION,
            'Bags and Purses': CAT_FASHION,
            'Bouquets': CAT_FURNITURE,
            'Cake Toppers': CAT_FURNITURE,
            'Candles': CAT_HOUSEHOLD,
            'Cards': CAT_FURNITURE,
            'Clothing': CAT_FASHION,
            'Decorations': CAT_FURNITURE,
            'Favors': CAT_HOUSEHOLD,
            'Frames': CAT_HOUSEHOLD,
            'Guest Books': CAT_HOUSEHOLD,
            'Invitations': CAT_HOUSEHOLD,
            'Jewelry': CAT_FASHION,
            'Just Married': CAT_HOUSEHOLD,
            'Men': CAT_FASHION,
            'Pillows': CAT_FURNITURE,
            'Portraits': CAT_HOUSEHOLD,
            'Something Blue': CAT_FASHION,
        },
        'Woodworking': {
            'Accessories': CAT_TOY_HOBBY,
            'Boxes': CAT_HOUSEHOLD,
            'Burning': CAT_HOUSEHOLD,
            'Carving': CAT_HOUSEHOLD,
            'Home Decor': CAT_FURNITURE,
            'Jewelry': CAT_FASHION,
            'Kitchen': CAT_HOUSEHOLD,
            'Miniature': CAT_TOY_HOBBY,
            'Office': CAT_OFFICE,
            'Outdoor': CAT_FURNITURE,
            'Sculptures': CAT_FURNITURE,
            'Seasonal': CAT_FURNITURE,
            'Signs': CAT_FURNITURE,
            'Sports': CAT_FURNITURE,
            'Supplies': CAT_OFFICE,
            'Toys': CAT_TOY_HOBBY,
        },
    },
    'Home': {
        'Artwork': {
            'Drawings': CAT_TOY_HOBBY,
            'Lithographs, Etchings & Woodcuts': CAT_FURNITURE,
            'Other': CAT_TOY_HOBBY,
            'Paintings': CAT_FURNITURE,
            'Photographs': CAT_FURNITURE,
            'Posters & Prints': CAT_FURNITURE,
        },
        'Bath': CAT_HOUSEHOLD,
        'Bedding': CAT_HOUSEHOLD,
        'Cleaning Supplies': CAT_HOUSEHOLD,
        'Furniture': CAT_FURNITURE,
        'Home Appliances': CAT_ELECTRONIC,
        'Home Décor': CAT_FURNITURE,
        "Kids' Home Store": {
            "Kids' Bath": CAT_FURNITURE,
            "Kids' Bedding": CAT_FURNITURE,
            "Kids' Flatware": CAT_HOUSEHOLD,
            "Kids' Furniture": CAT_FURNITURE,
            "Kids' Room Décor": CAT_FURNITURE,
            'Nursery Bedding': CAT_FURNITURE,
            'Nursery Décor': CAT_FURNITURE,
            'Nursery Furniture': CAT_FURNITURE,
        },
        'Kitchen & Dining': CAT_HOUSEHOLD,
        'Seasonal Décor': CAT_FURNITURE,
        'Storage & Organization': CAT_HOUSEHOLD,
    },
    'Kids': {
        'Bathing & Skin Care': {
            'Bathing Tubs & Seats': CAT_HOUSEHOLD,
            'Bathroom Safety': CAT_HOUSEHOLD,
            'Bubble Bath': CAT_HOUSEHOLD,
            'Conditioners': CAT_COSMETICS_BODY,
            'Grooming & Healthcare Kits': CAT_COSMETICS_BODY,
            'Non-Slip Bath Mats': CAT_HOUSEHOLD,
            'Shampoo': CAT_COSMETICS_BODY,
            'Skin Care': CAT_COSMETICS_BODY,
            'Soaps & Cleansers': CAT_COSMETICS_BODY,
            'Travel Bathing Kits': CAT_COSMETICS_BODY,
            'Washcloths & Towels': CAT_HOUSEHOLD,
        },
        'Boys (4+)': CAT_FASHION,
        'Boys 0-24 Mos': CAT_FASHION,
        'Boys 2T-5T': CAT_FASHION,
        'Car Seats & Accessories': {
            'Accessories': CAT_HOUSEHOLD,
            'Car Seats': CAT_HOUSEHOLD,
        },
        'Diapering': {
            'Changing Kits': CAT_HOUSEHOLD,
            'Changing Pads & Covers': CAT_HOUSEHOLD,
            'Changing Tables': CAT_FURNITURE,
            'Cloth Diapers': CAT_FASHION,
            'Diaper Bags': CAT_FASHION,
            'Diaper Pails & Refills': CAT_HOUSEHOLD,
            'Diaper Stackers & Caddies': CAT_HOUSEHOLD,
            'Disposable Diapers': CAT_HEALTH,
            'Powders & Lotions': CAT_HEALTH,
            'Washcloths & Towels': CAT_HOUSEHOLD,
            'Wipes & Holders': CAT_HEALTH,
        },
        'Feeding': {
            'Bottle-Feeding': CAT_FOOD_BEV,
            'Breastfeeding': CAT_HOUSEHOLD,
            'Gift Sets': CAT_HOUSEHOLD,
            'Highchairs & Booster Seats': CAT_FURNITURE,
            'Pacifiers & Accessories': CAT_HOUSEHOLD,
            'Pillows & Stools': CAT_HOUSEHOLD,
            'Storage & Containers': CAT_HOUSEHOLD,
        },
        'Gear': {
            'Activity Centers & Entertainers': CAT_TOY_HOBBY,
            'Baby Gyms & Playmats': CAT_HOUSEHOLD,
            'Baby Seats': CAT_FURNITURE,
            'Backpacks & Carriers': CAT_FASHION,
            'Bicycle Child Seats & Trailers': CAT_TOY_HOBBY,
            'Harnesses & Leashes': CAT_HEALTH,
            'Playard Bedding': CAT_HOUSEHOLD,
            'Playards': CAT_HOUSEHOLD,
            'Shopping Cart Covers': CAT_HEALTH,
            'Swings, Jumpers & Bouncers': CAT_HOUSEHOLD,
            'Travel Beds': CAT_HOUSEHOLD,
            'Walkers': CAT_HOUSEHOLD,
        },
        'Girls (4+)': CAT_FASHION,
        'Girls 0-24 Mos': CAT_FASHION,
        'Girls 2T-5T': CAT_FASHION,
        'Health & Baby Care': {
            'Humidifiers & Vaporizers': CAT_HEALTH,
            'Nail Care': CAT_COSMETICS_BODY,
            'Nasal Aspirators': CAT_COSMETICS_BODY,
            'Sun Protection': CAT_COSMETICS_BODY,
            'Teethers': CAT_HEALTH,
            'Teething Relief': CAT_HEALTH,
            'Thermometers': CAT_HEALTH,
            'Toothbrushes': CAT_COSMETICS_BODY,
        },
        'Nursery': {
            'Bedding': CAT_HOUSEHOLD,
            'Furniture': CAT_FURNITURE,
            'Nursery Décor': CAT_FURNITURE,
        },
        'Potty Training': {
            'Potties & Seats': CAT_HOUSEHOLD,
            'Seat Covers': CAT_HOUSEHOLD,
            'Step Stools': CAT_HOUSEHOLD,
            'Training Pants': CAT_HEALTH,
        },
        'Pregnancy & Maternity': {
            'Breastfeeding Pillows & Stools': CAT_HOUSEHOLD,
            'Family Planning Tests': CAT_HEALTH,
            'Maternity Pillows': CAT_HOUSEHOLD,
            'Prenatal Monitoring Devices': CAT_HEALTH,
        },
        'Safety': {
            'Bathroom Safety': CAT_HOUSEHOLD,
            'Cabinet Locks & Straps': CAT_HEALTH,
            'Crib Netting': CAT_FURNITURE,
            'Edge & Corner Guards': CAT_FURNITURE,
            'Electrical Safety': CAT_HEALTH,
            'Gates & Doorways': CAT_HOUSEHOLD,
            'Harnesses & Leashes': CAT_HEALTH,
            'Kitchen Safety': CAT_HEALTH,
            'Monitors': CAT_ELECTRONIC,
            'Outdoor Safety': CAT_HEALTH,
            'Rails & Rail Guards': CAT_HEALTH,
            'Safety Caps': CAT_HEALTH,
            'Sleep Positioners': CAT_HOUSEHOLD,
        },
        'Strollers': CAT_HOUSEHOLD,
        'Toys': CAT_TOY_HOBBY,
    },
    'Men': CAT_FASHION,
    'Other': {
        'Automotive': {
            'Automotive Enthusiast Merchandise': CAT_TOY_HOBBY,
            'Car Care': CAT_HOUSEHOLD,
            'Car Electronics & Accessories': CAT_ELECTRONIC,
            'Exterior Accessories': CAT_FURNITURE,
            'Interior Accessories': CAT_FURNITURE,
            'Lights & Lighting Accessories': CAT_HOUSEHOLD,
            'Motorcycle & Powersports': CAT_TOY_HOBBY,
            'Oils & Fluids': CAT_DIGITAL_SERVICES,
            'Paint, Body & Trim': CAT_HOUSEHOLD,
            'Performance Parts & Accessories': CAT_HOUSEHOLD,
            'RV Parts & Accessories': CAT_HOUSEHOLD,
            'Replacement Parts': CAT_HOUSEHOLD,
            'Tires & Wheels': CAT_HOUSEHOLD,
            'Tools & Equipment': CAT_HOUSEHOLD,
        },
        'Books': CAT_MEDIA,
        'Daily & Travel items': {
            'Baby & Child Care': CAT_HOUSEHOLD,
            'Health Care': CAT_HEALTH,
            'Household Supplies': CAT_HOUSEHOLD,
            'Medical Supplies & Equipment': CAT_OFFICE,
            'Personal Care': CAT_COSMETICS_BODY,
            'Sports Nutrition': CAT_FOOD_BEV,
            'Stationery & Party Supplies': CAT_HOUSEHOLD,
        },
        'Magazines': CAT_MEDIA,
        'Musical instruments': {
            'Amplifiers & Effects': CAT_ELECTRONIC,
            'Band & Orchestra': CAT_TOY_HOBBY,
            'Bass Guitars': CAT_TOY_HOBBY,
            'Brass Instruments': CAT_TOY_HOBBY,
            'DJ, Electronic Music & Karaoke': CAT_ELECTRONIC,
            'Drums & Percussion': CAT_TOY_HOBBY,
            'Guitars': CAT_TOY_HOBBY,
            'Instrument Accessories': CAT_TOY_HOBBY,
            'Keyboards': CAT_ELECTRONIC,
            'Live Sound & Stage': CAT_TOY_HOBBY,
            'Microphones & Accessories': CAT_ELECTRONIC,
            'Stringed Instruments': CAT_TOY_HOBBY,
            'Studio Recording Equipment': CAT_ELECTRONIC,
            'Wind & Woodwind Instruments': CAT_TOY_HOBBY,
        },
        'Office supplies': CAT_OFFICE,
        'Pet Supplies': CAT_PET,
    },
    'Sports & Outdoors': {
        'Apparel': CAT_FASHION,
        'Exercise': {
            'Athletic Training': CAT_TOY_HOBBY,
            'Bowling': CAT_TOY_HOBBY,
            'Boxing & MMA': CAT_TOY_HOBBY,
            'Dance/Ballet': CAT_TOY_HOBBY,
            'Fitness accessories': CAT_HOUSEHOLD,
            'Fitness technology': CAT_ELECTRONIC,
            'Other': CAT_HOUSEHOLD,
            'Strength training': CAT_HOUSEHOLD,
            'Track & Field': CAT_TOY_HOBBY,
            'Yoga & Pilates': CAT_TOY_HOBBY,
        },
        'Fan Shop': CAT_FASHION,
        'Footwear': CAT_FASHION,
        'Golf': {
            'Electronics': CAT_ELECTRONIC,
            'Golf Apparel': CAT_FASHION,
            'Golf Bags': CAT_TOY_HOBBY,
            'Golf Balls': CAT_TOY_HOBBY,
            'Golf Shoes': CAT_FASHION,
            "Men's Golf Clubs": CAT_TOY_HOBBY,
            "Women's Golf Clubs": CAT_TOY_HOBBY,
        },
        'Other': CAT_HOUSEHOLD,
        'Outdoors': CAT_TOY_HOBBY,
        'Team Sports': CAT_TOY_HOBBY,
    },
    'Vintage & Collectibles': {
        'Accessories': CAT_FASHION,
        'Antique': {
            '100 Years or Older': CAT_TOY_HOBBY,
            '50 To 75 Years': CAT_TOY_HOBBY,
            '75 To 100 Years': CAT_TOY_HOBBY,
            'Accessories': CAT_TOY_HOBBY,
            'Bags and Purses': CAT_FASHION,
            'Book': CAT_MEDIA,
            'Collectibles': CAT_TOY_HOBBY,
            'Electronics': CAT_ELECTRONIC,
            'Furniture': CAT_FURNITURE,
            'Home Decor': CAT_FURNITURE,
            'Housewares': CAT_HOUSEHOLD,
            'Jewelry': CAT_FASHION,
            'Other': CAT_TOY_HOBBY,
            'Paper Ephemera': CAT_TOY_HOBBY,
            'Serving': CAT_HOUSEHOLD,
            'Supplies': CAT_HOUSEHOLD,
            'Toy': CAT_TOY_HOBBY,
        },
        'Bags and Purses': {
            'Case': CAT_HOUSEHOLD,
            'Change Purse': CAT_FASHION,
            'Clutch': CAT_FASHION,
            'Diaper Bag': CAT_HOUSEHOLD,
            'Formal': CAT_FASHION,
            'Handbag': CAT_FASHION,
            'Leather': CAT_FASHION,
            'Luggage': CAT_HOUSEHOLD,
            'Other': CAT_FASHION,
            'Pouch': CAT_FASHION,
            'Purse': CAT_FASHION,
            'Tote': CAT_FASHION,
            'Wallet': CAT_HOUSEHOLD,
        },
        'Book': {
            'Art': CAT_TOY_HOBBY,
            'Biography': CAT_MEDIA,
            'Children': CAT_MEDIA,
            'Comics': CAT_MEDIA,
            'Cookbook': CAT_FOOD_BEV,
            'Crafting': CAT_TOY_HOBBY,
            'Decorating': CAT_FURNITURE,
            'Fiction': CAT_MEDIA,
            'Health': CAT_HEALTH,
            'History': CAT_MEDIA,
            'How to': CAT_TOY_HOBBY,
            'Illustrated': CAT_MEDIA,
            'Instructional': CAT_TOY_HOBBY,
            'Nonfiction': CAT_MEDIA,
            'Other': CAT_MEDIA,
            'Poetry': CAT_MEDIA,
            'Reference': CAT_MEDIA,
            'Religion': CAT_MEDIA,
            'Science': CAT_MEDIA,
            'Scifi': CAT_MEDIA,
        },
        'Clothing': CAT_FASHION,
        'Collectibles': CAT_TOY_HOBBY,
        'Electronics': CAT_ELECTRONIC,
        'Furniture': CAT_FURNITURE,
        'Home Decor': CAT_FURNITURE,
        'Housewares': CAT_HOUSEHOLD,
        'Jewelry': CAT_FASHION,
        'Paper Ephemera': {
            'Advertisement': CAT_MEDIA,
            'Game': CAT_MEDIA,
            'Map': CAT_HOUSEHOLD,
            'Other': CAT_HOUSEHOLD,
            'Postcard': CAT_TOY_HOBBY,
            'Stamps': CAT_TOY_HOBBY,
        },
        'Serving': CAT_HOUSEHOLD,
        'Supplies': {
            'Bead': CAT_TOY_HOBBY,
            'Button': CAT_TOY_HOBBY,
            'Cabochon': CAT_TOY_HOBBY,
            'Chain': CAT_FASHION,
            'Charm': CAT_FASHION,
            'Ephemera': CAT_TOY_HOBBY,
            'Fabric': CAT_TOY_HOBBY,
            'Finding': CAT_TOY_HOBBY,
            'Other': CAT_TOY_HOBBY,
            'Pattern': CAT_TOY_HOBBY,
            'Trim': CAT_TOY_HOBBY,
            'Yarn': CAT_TOY_HOBBY,
            'Zipper': CAT_TOY_HOBBY,
        },
        'Toy': CAT_TOY_HOBBY,
        'Trading Cards': CAT_TOY_HOBBY,
    },
    'Women': CAT_FASHION,
}